export const UserAttributes = {
  ACCEPT_MENTORING: 'acceptMentoring',
  TAGS: 'tags',
  CALENDLY_URL: 'calendyUrl',
  LINKEDIN: 'linkedin',
  FACEBOOK: 'facebook',
  INSTAGRAM: 'instagram',
  COUNTRY_CODE: 'countryCode',
  TIMEZONE: 'timezone',
  TITLE: 'title',
  AVAILABLE_TIME: 'availableTime',
  DESC_WHAT_CAN_I_HELP: 'descWhatCanIHelp',
  DESC_ACHIVEMENT: 'descAchivement',
  DESC_SKILL: 'descSkill',
  DESC_OTHER: 'descOther',
  DESC_MENTORS_NOTICE: 'descMentorsNotice',
}
